import Header from '@/components/Header';
import Hero from '@/components/Hero';
import Motion from '@/components/Motion';
import Expertise from '@/components/Expertise';
import Portfolio from '@/components/Portfolio';
import Contact from '@/components/Contact';
import {Arrow,Mark} from '@/components/Icons';
export default function Home(){
 return <><Header/><main id="main"><Hero/>
 <section className="intro section-pad" aria-labelledby="intro-heading">
 <div className="section-tag"><span className="dot"/> THE INVISIBLE, MADE ESSENTIAL.</div>
 <div className="intro-content"><h2 id="intro-heading" data-reveal>Great spaces are felt.<br/><span className="muted">The engineering behind<br/>them should be, too.</span></h2>
 <div className="intro-bottom"><p>From the first drawing to the final handover, we bring HVAC and MEP systems together. Considered design. Precise execution. Buildings ready for life.</p><a href="#expertise" className="text-link">Meet the systems <Arrow/></a></div></div>
 <div className="partner-strip"><span className="mono">TECHNOLOGY PARTNERS<br/><small>As listed in our portfolio</small></span><span className="carrier-word">Carrier</span><span className="toshiba-word">TOSHIBA</span><span className="teletask-word"><i>▦</i> TELETASK</span></div>
 </section>
 <Expertise/><Portfolio/>
 <section className="impact section-pad" aria-labelledby="impact-heading"><div className="section-tag"><span className="dot"/> DELIVERY, IN NUMBERS.</div>
 <div className="impact-heading"><h2 id="impact-heading" data-reveal>Big systems.<br/><em>Real delivery.</em></h2><p>Two milestones from our portfolio.<br/>A closer look at what execution means.</p></div>
 <div className="impact-grid"><article data-reveal><div className="mono">01 / HEALTHCARE</div><div className="impact-number">950<span>TR</span></div><div className="impact-line"><strong>45 days.</strong><span>Stanley Government Hospital<br/>VRF + DX systems</span></div></article>
 <article data-reveal><div className="mono">02 / EDUCATION</div><div className="impact-number">400<span>TR</span></div><div className="impact-line"><strong>15 days.</strong><span>SRMIST, Ramapuram<br/>Om Vinayaga Hostel Block</span></div></article></div><p className="fine-print">Milestones reported in MAC’s portfolio. SRMIST’s hostel milestone is distinct from the 425-capacity university project entry.</p>
 </section>
 <section className="approach section-pad" id="approach" aria-labelledby="approach-heading"><div className="section-tag"><span className="dot"/> A CLEAR PATH FORWARD.</div><div className="section-heading"><h2 id="approach-heading" data-reveal>Drawn with intent.<br/>Delivered with care.</h2><p>One coordinated process.<br/>From the first line to a working system.</p></div>
 <div className="process-grid">{[['Shop drawing','Engineering begins with a coordinated technical plan.'],['Approval','A shared direction before execution begins.'],['Procurement & installation','Equipment and installation brought together on site.'],['Testing & commissioning','Systems checked and prepared for operation.'],['Handover','The completed work, ready for its next chapter.']].map(([title,body],i)=><article key={title} data-reveal><span className="process-number">0{i+1}</span><div className="process-track"><span/></div><h3>{title}</h3><p>{body}</p></article>)}</div><div className="aftercare"><span className="mono">BEYOND HANDOVER</span><span>Maintenance</span><span>Onsite support</span><span>Operational training</span><Arrow/></div>
 </section>
 <section className="history section-pad" id="about" aria-labelledby="history-heading"><div className="section-tag"><span className="dot"/> CHENNAI ROOTS. ENGINEERING AMBITION.</div>
 <div className="history-grid"><div className="history-title"><h2 id="history-heading" data-reveal>Built over time.<br/><em>Better with<br/>every project.</em></h2><p>MAC Engineering Services brings more than 15 years of industry experience to the spaces where people work, learn, recover and live.</p><div className="history-signature">MAC<span>EST. 2010 / CHENNAI</span></div></div>
 <div className="timeline">{[['2010','The beginning.','MAC Engineering Services is founded in Chennai, Tamil Nadu.'],['2014','A stronger foundation.','Formal registration marks an expansion in engineering capabilities and HVAC system design.'],['2021—','A connected approach.','The portfolio describes a growing MEP practice, with project execution, onsite support and operational training.']].map(([year,title,body])=><article key={year} data-reveal><span className="timeline-dot"/><span className="timeline-year">{year}</span><h3>{title}</h3><p>{body}</p></article>)}</div></div>
 <div className="leadership"><div className="portrait-wrap"><img src="/images/principal.webp" alt="Founding principal of MAC Engineering Services, as pictured in the company portfolio" width="512" height="768" loading="lazy"/></div><div><span className="mono">THE PEOPLE BEHIND THE SYSTEMS</span><h3>Technical excellence.<br/>Personal commitment.</h3><p>Hands-on involvement in major project execution. A belief that quality is built into every installation, from the drawing board to the site.</p><span className="mono">FOUNDING PRINCIPAL / MAC ENGINEERING SERVICES</span></div></div>
 <div className="values-grid">{[['Our vision','Market leadership. Sustainability. Impact.'],['Our mission','Delivery. Expertise. Reliability.'],['Our values','Safety first. Technical excellence. Cooperation.']].map(([title,text],i)=><article key={title}><span className="mono">0{i+1}</span><h3>{title}</h3><p>{text}</p></article>)}</div>
 </section>
 <section className="current-work section-pad"><div className="section-heading"><div><div className="section-tag"><span className="dot"/> THE NEXT CHAPTER.</div><h2 data-reveal>Engineering in progress.</h2></div><p className="fine-print">Status as reported in the portfolio.<br/>Contact us for the latest project updates.</p></div><div className="current-grid">{[['bosch','BOSCH Limited','Adugodi','Chilled water 520 · VRF 15','Cooling capacities as listed'],['caplin','CAPLIN','Heat recovery','12,000 CFM','Heat recovery wheel'],['bharat','Bharat Silks','Bangalore','42,000 CFM','Ventilation']].map(([image,name,place,figure,system])=><article key={image} data-reveal><img src={'/images/'+image+'.webp'} alt={name+' project image from the MAC portfolio'} width="600" height="400" loading="lazy"/><div className="current-meta"><h3>{name}</h3><span>{place}</span></div><strong>{figure}</strong><p>{system}</p></article>)}</div></section>
 <Contact/></main><footer className="footer"><a href="/" aria-label="Back to home"><Mark/></a><div className="footer-links"><a href="#expertise">Expertise</a><a href="#work">Projects</a><a href="/portfolio" target="_blank" rel="noopener">Portfolio PDF ? 51 MB <Arrow diagonal/></a><a href="/privacy">Privacy</a></div><span className="mono">CHENNAI, INDIA / © {new Date().getFullYear()} MAC</span></footer><Motion/></>;
}
